plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
    id 'com.gradleup.shadow' version '9.4.1'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
    maven { url = 'https://maven.maxhenkel.de/repository/public' }
    maven { url = "https://maven.lavalink.dev/releases" }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

configurations {
    shadowImplementation
    implementation.extendsFrom shadowImplementation
}

dependencies {
    // Fabric 26.1 standard: Loom uses standard implementation now
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // simple voice chat
    implementation "de.maxhenkel.voicechat:voicechat-api:2.6.13"
    runtimeOnly "maven.modrinth:simple-voice-chat:fabric-2.6.17+26.1.2"

    // lavaplayer and stuff updated
    shadowImplementation 'dev.arbjerg:lavaplayer:2.2.7'
    shadowImplementation 'dev.lavalink.youtube:v2:1.18.2'
    shadowImplementation 'org.apache.httpcomponents:httpclient:4.5.14'

    // Additional dependencies
    include 'org.jsoup:jsoup:1.22.2'
    include 'net.iharder:base64:2.3.9'
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

shadowJar {
    configurations = [project.configurations.shadowImplementation]
    archiveClassifier = 'shadow-dev'

    relocate 'org.apache.http', 'dev.derock.svcmusic.apachehttp'
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn shadowJar
    archiveClassifier.set("")

    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }

    from {
        zipTree(shadowJar.archiveFile.get().asFile)
    }
}

jar {
    dependsOn shadowJar

    archiveClassifier.set("")
    from {
        zipTree(shadowJar.archiveFile.get().asFile)
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
    }
}
